chat/urls.py
# coding: utf-8
from django.conf.urls import *
from chat.views import PrincipalView,InicioView


urlpatterns = patterns('',

url(r'^$', PrincipalView.as_view()),
url(r'^inicio/$', InicioView.as_view()),
url(r'^comentar/$', 'chat.views.comentar'),

)

webGG/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
from webpage.views import *
from django.contrib.auth.decorators import login_required

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'webpage.views.login'),
    url(r'^logout/$', 'webpage.views.logout'),
    url(r'^administracion/$', login_required(GrupoguaView.as_view())),
    url(r'^$', PrincipalView.as_view()),
    url(r'^municipio/', include('webpage.urls')),
    
    #url(r'^tadese/consultapadrones.php?id=(?P<codigo>\d{1,3})','django.views.generic.simple.redirect_to',{'url': 'http://www.boletaweb.com.ar/municipios/consultapadrones.php?id=%(codigo)s'}),


)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

chat/models.py
from django.db import models

# Create your models here.
class Comentario(models.Model):
	usuario = models.CharField(max_length=50)
	descripcion = models.TextField()
	fechayHora = models.DateTimeField(auto_now_add=True)

chat/forms.py
from django import forms
from .models import Comentario

class CommentForm(forms.ModelForm):

	class Meta:
		model = Comentario

chat/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView
# Create your views here.
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse

from .forms import CommentForm
from .models import Comentario
import json

from datetime import date
hoy = date.today()

class PrincipalView(TemplateView):
    template_name = 'chat/chat.html'

    def post(self,request,*args,**kwargs):
        request.session['nombre'] = request.POST['nombre']
        return redirect('inicio/')

class InicioView(TemplateView):

    def get(self,request,*args,**kwargs):
        if request.session.get('nombre'):
            comentarios = Comentario.objects.filter(fechayHora__gt=hoy).order_by('-fechayHora')
            dic = {
                'nombre' : request.session['nombre'],
                'form' : CommentForm(),
                'comentarios' : comentarios,
                }
            return render(request,'chat/inicio.html',dic)
        else:
            return redirect('/chat/')

    def post(self,request,*args,**kwargs):
        Comentario.objects.create(
            usuario = request.session['nombre'],
            descripcion = request.POST['descripcion'],
            fechayHora = datetime.datetime.now()
            )
        return redirect('/chat/inicio')

@csrf_exempt
def comentar(request):
    Comentario.objects.create(
        usuario = request.POST.get('usuario'),
        descripcion = request.POST.get('descripcion')
        )
    response = {'usuario' : request.POST['usuario'],'descripcion': request.POST['descripcion'],}
    
    return HttpResponse(json.dumps(response),content_type='application/json')

templates/chat/chat.html
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge" charset="utf-8">
{% load static from staticfiles %}
<link rel="shortcut icon" type="image/png" href="{% static 'images/logo.png' %}">
<title>Grupo Guadalupe Sistemas</title>


</head>
<body>
 <h1>Ingrese al Chat</h1>
 <form method="POST">
  {% csrf_token %}
  <input type="text" name="nombre" placeholder="Ingrese su Nombre">
  <input type="submit" value="Ingrese su Nombre">
 </form>
</body>
</html>

templates/chat/inicio.html
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge" charset="utf-8">
{% load static from staticfiles %}
<link rel="shortcut icon" type="image/png" href="{% static 'images/logo.png' %}">
<title>Grupo Guadalupe Sistemas</title>


</head>
<body>
 <h1>Hola {{nombre}}!!</h1>
<hr>
<div id="comentarios">
{% for com in comentarios %}
	<p>{{ com.usuario}} - {{ com.fechayHora}} - {{com.descripcion}}</p>
{% endfor %}
</div>
 <form>
 	{% csrf_token %}
 	{{ form.descripcion }}
 	<button id="boton">Comentar</button>
 </form>

</body>
</html>

<script type="text/javascript" src="{% static 'css/bootstrap/js/jquery-1.11.0.js' %}"></script>
<script src= "http://localhost:3000/socket.io/socket.io.js"type="text/javascript"></script>
<script>
	var socket = io.connect("http://localhost:3000");

	$('#boton').on('click',Comentar);

	function Comentar(e){
		e.preventDefault();
		var datos = {
			usuario : "{{ nombre }}",
			descripcion : $('#id_descripcion').val(),
		}
		socket.emit('nuevo comentario',datos);
	}
	socket.on('devolviendo comentario',function (data){
		var data = JSON.parse(data);
		var d = new Date();
		$('#comentarios').prepend("<p>"+data.usuario+" - "+
			d.getDate() + "/" + (d.getMonth() +1) + "/" + d.getFullYear()+" "+d.getHours()+':'+d.getMinutes()+':'+d.getSeconds()+" - "+data.descripcion+"</p>");
	});

</script>